language: node_js
os:
 - linux
node_js:
  - "11"
  - "10"
  - "8"
  - "6"
cache:
  directories:
    - "node_modules"
notifications:
  email: false
matrix:
  fast_finish: true
  include:
    - node_js: "lts/*"
      env: PRETEST=true
script:
  - 'if [ -n "${PRETEST-}" ]; then yarn run pretest ; fi'
  - 'if [ -n "${TEST-}" ]; then yarn run tests-only ; fi'
sudo: false